# Generated by Django 5.1.4 on 2024-12-22 17:28

import dbapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_text',
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_en',
            field=models.TextField(blank=True, help_text='Prompt text in English', null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_text_kn',
            field=models.TextField(blank=True, help_text='Prompt text in Kannada', null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='language',
            field=models.CharField(choices=[(dbapp.models.LanguageEnum['ENGLISH'], 'en'), (dbapp.models.LanguageEnum['KANNADA'], 'kn')], default=dbapp.models.LanguageEnum['ENGLISH'], max_length=2),
        ),
    ]
