# Generated by Django 5.1.4 on 2024-12-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_remove_prompt_prompt_text_prompt_prompt_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_text_en',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_text_kn',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_type',
        ),
        migrations.AddField(
            model_name='prompt',
            name='primary_prompt',
            field=models.TextField(blank=True, help_text='Primary prompt text', null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='suggestion_prompt',
            field=models.TextField(blank=True, help_text='Suggestion prompt text', null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='summary_prompt',
            field=models.TextField(blank=True, help_text='Summary prompt text', null=True),
        ),
    ]
