# Generated by Django 5.1.4 on 2024-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_remove_prompt_prompt_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='language',
            field=models.CharField(choices=[('en', 'ENGLISH'), ('kn', 'KANNADA')], default='en', max_length=2),
        ),
    ]
